esupotp[0].name=mfa-esupotp
esupotp[0].rank=0
esupotp[0].urlApi=http://localhost:3000/
esupotp[0].usersSecret=changeit
esupotp[0].apiPassword=changeit
esupotp[0].byPassIfNoEsupOtpMethodIsActive=false
esupotp[0].otpManagerUrl=http://localhost:4000/

esupotp[1].name=mfa-esupotp-ext
esupotp[1].rank=1
esupotp[1].urlApi=http://localhost:3001/
esupotp[1].usersSecret=changeit
esupotp[1].apiPassword=changeit
esupotp[1].byPassIfNoEsupOtpMethodIsActive=false
esupotp[1].otpManagerUrl=http://localhost:4001/


